### ISSUE TITLE
Request for endorsement of my paper

### ISSUE THREAD

**Issue by Tharun-tharun** [TheGalileo/Image-Inpainting-Sparse-Representation#1]
Hi Gaurav Verma,

I'm Tharun P pursuing my final year CSE, I'm about to finish my UG program by next month. I would like to publish my paper on arXiv (CS), made a small study on my research paper based on artificial intelligence. So I need a moderator for my paper to submit the paper.

Since it's asking for an endorsement for my paper, So I need help in submitting my paper, I request you as an endorser to submit an article to the cs.AI section of arXiv.

Regards
Tharun P

**Comment by gaurav22verma** [comment]
Hi Tharun, this seems to be unrelated to this GitHub repo; I will close the issue here. Please feel free to drop me an email.

**Comment by Tharun-tharun** [comment]
Dear Gaurav Verma,

I'm Tharun P pursuing my final year CSE, I'm about to finish my UG program
by next month. I would like to publish my paper on arXiv (CS). I made a
small study on my research paper based on artificial intelligence. So I
need a moderator for my paper to submit the paper. Since it's asking for an
endorsement for my paper, So I need help in submitting my paper, I request
you as an endorser to submit an article to the cs.AI section of arXiv.
